In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [2]:
reviews =['nice food',
         'amazing restaurant',
         'too good',
         'just loved it!',
         'will go gain',
         'horrible food',
         'never go their',
         'poor service',
         'poor quality',
         'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size)for d in reviews]
encoded_reviews

[[13, 24],
 [9, 19],
 [22, 28],
 [8, 17, 3],
 [21, 21, 20],
 [12, 24],
 [19, 21, 19],
 [14, 22],
 [14, 20],
 [5, 11]]

In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[13, 24,  0,  0],
       [ 9, 19,  0,  0],
       [22, 28,  0,  0],
       [ 8, 17,  3,  0],
       [21, 21, 20,  0],
       [12, 24,  0,  0],
       [19, 21, 19,  0],
       [14, 22,  0,  0],
       [14, 20,  0,  0],
       [ 5, 11,  0,  0]])

In [5]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 20)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(X,y, epochs=50, verbose=0)

In [9]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 308ms/step - loss: 0.6403 - accuracy: 1.0000


1.0

In [12]:
model.get_layer('embedding').get_weights()[0]

array([[-0.03084739, -0.0613312 , -0.02237623, -0.07257037, -0.02100234],
       [ 0.049535  ,  0.0341311 , -0.01143591,  0.02552456,  0.01103712],
       [ 0.03533758,  0.03344348, -0.01499534, -0.02671777,  0.04124557],
       [ 0.0021393 ,  0.0063066 ,  0.09029645,  0.0248194 ,  0.00479714],
       [-0.02331606, -0.01816975, -0.02646219,  0.01949502,  0.01790842],
       [-0.00449317,  0.0150973 , -0.07378511, -0.00759497, -0.08679389],
       [ 0.02257245, -0.04011675, -0.03404178, -0.0468586 ,  0.0293037 ],
       [-0.03699682,  0.04254173,  0.00697057, -0.02694331, -0.02840623],
       [ 0.04351164, -0.01325487,  0.0939906 ,  0.07874104,  0.08148712],
       [ 0.05381473, -0.0177476 ,  0.01113612,  0.07742319,  0.01505424],
       [-0.03710346,  0.04917438,  0.00136663,  0.03812711,  0.02472634],
       [ 0.06122091,  0.09129803, -0.02250154,  0.09165137, -0.05966406],
       [-0.06203581,  0.02144977, -0.02280871, -0.0142527 , -0.04974744],
       [ 0.07400556, -0.0734662 ,  0.0

In [13]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [15]:
weights[13]

array([ 0.07400556, -0.0734662 ,  0.02288556,  0.09413833,  0.01740247],
      dtype=float32)

In [16]:
weights[9]

array([ 0.05381473, -0.0177476 ,  0.01113612,  0.07742319,  0.01505424],
      dtype=float32)