### Word Embedding Techniques using Embedding Layers in Keras 

In [1]:
## Libraries used Tensorflow >2.0 and keras

In [2]:
#tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## vocubulary size
voc_size = 10000

### One Hot Representation

In [7]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[5695, 1167, 2574, 9941], [5695, 1167, 2574, 3154], [5695, 6852, 2574, 7773], [3531, 5680, 9875, 6072, 9161], [3531, 5680, 9875, 6072, 8173], [1237, 5695, 8544, 2574, 468], [9844, 4239, 5060, 6072]]


### Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5695 1167 2574 9941]
 [   0    0    0    0 5695 1167 2574 3154]
 [   0    0    0    0 5695 6852 2574 7773]
 [   0    0    0 3531 5680 9875 6072 9161]
 [   0    0    0 3531 5680 9875 6072 8173]
 [   0    0    0 1237 5695 8544 2574  468]
 [   0    0    0    0 9844 4239 5060 6072]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948
   -0.04085312  0.02472297 -0.04731562  0.04296141  0.02100467]
  [-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948
   -0.04085312  0.02472297 -0.04731562  0.04296141  0.02100467]
  [-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948
   -0.04085312  0.02472297 -0.04731562  0.04296141  0.02100467]
  [-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948
   -0.04085312  0.02472297 -0.04731562  0.04296141  0.02100467]
  [ 0.00660871 -0.00552651  0.02974364 -0.03418376 -0.00180398
    0.00879347 -0.0264993  -0.02302557  0.02636025  0.01407364]
  [-0.02453737  0.04688437  0.00878277 -0.00963857 -0.0412836
    0.04110818  0.01632826 -0.03498384  0.01915851  0.02331891]
  [-0.04365391  0.01586307 -0.01179485  0.00305004  0.00647616
    0.03056123  0.03510419 -0.03269887  0.03926386 -0.04406404]
  [ 0.02320211 -0.00903285 -0.04524254 -0.0154719   0.04764656
    0.02778479  0.04566802 -0.02872235 -0.03444143  0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 5695, 1167, 2574, 9941])

In [16]:
print(model.predict(embedded_docs)[0])

[[-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948  -0.04085312
   0.02472297 -0.04731562  0.04296141  0.02100467]
 [-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948  -0.04085312
   0.02472297 -0.04731562  0.04296141  0.02100467]
 [-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948  -0.04085312
   0.02472297 -0.04731562  0.04296141  0.02100467]
 [-0.03450435 -0.00588517  0.02803816 -0.0006578  -0.0369948  -0.04085312
   0.02472297 -0.04731562  0.04296141  0.02100467]
 [ 0.00660871 -0.00552651  0.02974364 -0.03418376 -0.00180398  0.00879347
  -0.0264993  -0.02302557  0.02636025  0.01407364]
 [-0.02453737  0.04688437  0.00878277 -0.00963857 -0.0412836   0.04110818
   0.01632826 -0.03498384  0.01915851  0.02331891]
 [-0.04365391  0.01586307 -0.01179485  0.00305004  0.00647616  0.03056123
   0.03510419 -0.03269887  0.03926386 -0.04406404]
 [ 0.02320211 -0.00903285 -0.04524254 -0.0154719   0.04764656  0.02778479
   0.04566802 -0.02872235 -0.03444143  0.02988205]]